//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B8_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Vintage { get; set; }
        public string CatalogyID { get; set; }
        public string Image { get; set; }
        public string Region { get; set; }
    
        public virtual Catalogy Catalogy { get; set; }
    }
}
